name: Integraton Test

on: [pull_request_target]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-node@v2.1.5
        with:
          version: 12
      - name: Markdown SEO Check
        uses: ./
        with:
          includes: 'test/pass/*.md'
          max_title_length: 70
          max_description_length: 150
          max_slug_length: 100
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
